### ISSUE TITLE
CLDR data version 33 release

### ISSUE THREAD

**Issue by kipcole9** [elixir-cldr/cldr_languages#1]
Unicode Consortium released CLDR version 33 today and I have updated ex_cldr, ex_cldr_numbers, ex_cldr_lists, ex_cldr_dates_times,ex_unitsandex_money` to use the new data.

There aren't any new locales but I can see there are changes and additions to some language information. I found this upgrade to have no issues in any of my code so hopefully the same for you.

Just bump your version requirements to {ex_cldr, "~> 1.5.0} and hopefully you're good to go.

**Comment by LostKobrakai** [comment]
I've just pushed the update to using ex_cldr v2, which should resolve this :)
