### ISSUE TITLE
CLDR data 35.0.0 now embedded in ex_cldr version 2.6.0

### ISSUE THREAD

**Issue by kipcole9** [elixir-cldr/cldr_languages#4]
Just noting that CLDR version 35 is out and ex_cldr version 2.6.0 embeds that data.  It was a very easy update so I wouldn't expect you would need to make any changes but perhaps you could verify that all is OK with that release for this lib?

**Comment by LostKobrakai** [comment]
I just ran the tests with 2.6 and everythings green. Thanks for the heads up. I've currently no doctests depending on the cldr contents, so no need for a new version from my side.
